<a href="https://colab.research.google.com/github/sriram180427/solved-problems/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

NUMPY stands for numerical python, it is used to perform numeric computations.
It is used to perfom array operations insted of lists, because arrays are faster and meomery efficient then list.
If we want to work with NUMPY we need to install numpy library using cmd (pip install numpy).
After installation we need to import numoy module.(import numpy as np)


In [ ]:
import numpy as np
# convert list into array / create 1D,2D,3D array
l = [1,2,3,4,5] #1D
res = np.array(l)
print(res)
print(type(res))
print(type(l))

res = np.array([[1,2,3],[4,5,6]]) # 2D
print(res)
print(type(res))

res = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3D
print(res)
print(type(res))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [ ]:
res = np.zeros((3,3))
print(res)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
res = np.ones((3,3))
print(res)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
res = np.eye((3))
print(res)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
res = np.full((3,3),5)
print(res)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# how to generate Sequence numbers
res = np.arange(1,11,3)
print(res)

res = np.linspace(1,10,5) # prints the values between ranges with same diff
print(res)

res = np.random.randint(1,100,10) # random numbers between ranges
print(res)

res = np.random.rand(10) # random numbers between 0 and 1
print(res)

res = np.random.randn(10) # random numbers between -1 and 1
print(res)

res = np.random.random((3,3)) # random numbers between 0 and 1
print(res)

res = np.random.choice([1,2,3,4,5],2) # choose num randomly
print(res)

res = np.random.randint(1,100,(3,3)) # choose num randomly
print(res)

[ 1  4  7 10]
[ 1.    3.25  5.5   7.75 10.  ]
[56 67 93 84 45 34 37 87 51 17]
[0.15712735 0.85254725 0.22677827 0.92852402 0.38008201 0.83635572
 0.85891722 0.11767469 0.48627964 0.32668349]
[ 1.35424378  1.4829299   0.5475208  -0.15622989 -0.46902228 -0.06390713
  0.83093964  0.4100122  -1.26383195  0.7637595 ]
[[0.61538435 0.03314444 0.35443537]
 [0.71153316 0.171581   0.02419575]
 [0.57938852 0.71303319 0.49434046]]
[2 5]
[[48 49 96]
 [17 91 63]
 [75 80 85]]


In [ ]:
# how to know the size of matrix

res = np.array([[1,2,3],[4,5,6]])
print(res.shape)
print(res.size)
print(res.ndim)
print(res.reshape(3,2))
print(res.flatten())


(2, 3)
6
2
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
#how to do element wise operations
res = np.array([1,2,3,4,5])
res1 = np.array([6,7,8,9,10])
print(res+res1)
print(res-res1)
print(res*res1)
print(res/res1)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
res = np.array([[1,2,3,4,5,6]])
print(sum(res))
print(res.max())
print(res.min())
print(res.argmax())
print(res.argmin())
print(np.median(res))
print(np.mean(res))
print(np.cumsum(res))
print(np.cumprod(res))


[1 2 3 4 5 6]
6
1
5
0
3.5
3.5
[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]


In [ ]:
#Shallow copy..>
# shallow - view() the changes in origianl array will effect copt/ duplicate array
l = [1,2,3,4,6]
res = np.array(l)
k = res.view()
res[2] = 100
print(k)

[  1   2 100   4   6]


In [ ]:
# Deep copy..>
# we use copy() the changes in original array wont effect copird array

In [ ]:
# slicing 2D to find matrix
import numpy as np
res = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(res)
print(res[1:4, 2:6])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [ ]:
# v-stack, h-stack

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print(np.vstack((A,B)))
print(np.hstack((A,B)))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
